library(qualtRics)

dataSurvey <- read_survey("Pathway elicitation survey anon.csv")
dataSurvey <- dataSurvey[dataSurvey$StartDate > as.POSIXct("2023-07-10 16:00:00", tz = "UTC"),] # removes responses before the actual start of the survey (i.e., pilot runs, and so-called survey previews)
dataSurvey <- dataSurvey[dataSurvey$Progress==100 & !is.na(dataSurvey$Q1),] #only keep participants who finished the survey and who didn't leave Q1 blank

#67 responses, of which 3 were not usable because they were generated by genAI applications
round(median(dataSurvey$`Duration (in seconds)`)/60,0)
