---
title: "Example Data"
author: "Erin M. Buchanan"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Libraries

```{r}
library(rio)
library(dplyr)
```

# Data

```{r}
DF <- import("../SPAML-PSA/05_Data_real/data_processing/output_data/en_full_data.csv.gz")
stimuli <- import("../SPAML-PSA/04_Procedure/en/en_words.csv")

DF2 <- import("../SPAML-PSA/05_Data_real/data_processing/output_data/de_full_data.csv.gz")
stimuli_match <- import("../SPAML-PSA/03_Materials/matched_stimuli/de_matched.csv")
```

# Filter

```{r}
# select 20 words
small <- stimuli %>% 
  filter(type != "nonword") %>% 
  filter(type != "unrelated") %>% 
  pull(en_target) %>% 
  sample(., size = 20)

obs <- DF %>% 
  filter(word %in% small) %>% 
  pull(observation) %>% 
  unique() %>% 
  sample(., size = 1000)

DF_send <- DF %>% 
  filter(observation %in% obs)

nrow(DF_send)
length(unique(DF_send$observation))

write.csv(DF_send, 
       gzfile("en_sample_full.csv.gz"),
       row.names = F)

# convert to german words
small2 <- stimuli_match %>% 
  filter(en_target %in% small) %>% 
  pull(de_target)

obs2 <- DF2 %>% 
  filter(word %in% small2) %>% 
  pull(observation) %>% 
  unique() %>% 
  sample(., size = 1000)

DF_send2 <- DF2 %>% 
  filter(observation %in% obs2)

nrow(DF_send2)
length(unique(DF_send2$observation))

write.csv(DF_send2, 
       gzfile("de_sample_full.csv.gz"),
       row.names = F)

getwd()
```